const translations = {
  ru: {
    // Header
    nav_main: "Главная",
    nav_masters: "Мастера",
    nav_haircuts: "Стрижки",
    nav_catalog: "Каталог",
    nav_cart: "Корзина",
    nav_contacts: "Контакты",
    burger_menu: "Меню",
    // Footer
    footer_contacts: "Контакты",
    footer_phone_1: "+7 (812) 123-45-67",
    footer_phone_2: "+7 (911) 123-45-67",
    footer_address: "Новоостровский проспект, дом 36 лит.",
    footer_hours: "Режим работы",
    footer_hours_weekdays: "C 10:00 до 21:00 (Пн-Пт)",
    footer_hours_weekends: "С 11:00 до 20:00 (Сб-Вс)",
    footer_instagram: "Мы в Instagram",
    footer_copyright: "Copyright © 2017 - 2022",
    // Admin catalog page (static elements)
    search_placeholder: "Поиск...",
    search_button: "Найти",
    filter_category_label: "Категория:",
    filter_all: "Все",
    filter_price_label: "Цена:",
    price_min_placeholder: "От",
    price_max_placeholder: "До",
    filter_rating_label: "Рейтинг:",
    rating_any: "Любой",
    rating_3_plus: "3+",
    rating_4_plus: "4+",
    rating_4_5_plus: "4.5+",
    filter_sort_label: "Сортировка:",
    sort_default: "По умолчанию",
    sort_name_asc: "А-Я",
    sort_name_desc: "Я-А",
    sort_price_asc: "Дешевые",
    sort_price_desc: "Дорогие",
    no_results: "Товары не найдены",
    button_save_changes: "Сохранить изменения",
    button_add_product: "Добавить товар",
    // Admin catalog page (dynamic elements)
    new_product: "Новый товар",
    placeholder_product_id: "ID продукта (уникальный)",
    placeholder_product_name: "Название",
    placeholder_product_price: "Цена",
    placeholder_product_description: "Описание",
    placeholder_product_rating: "Рейтинг",
    placeholder_product_image: "Путь к изображению",
    button_delete_product: "Удалить товар",
    button_cancel_add: "Отменить добавление",
    // Categories
    category_face: "Лицо",
    category_body: "Тело",
    category_make_up: "Макияж",
    category_hairs: "Волосы",
    // Notifications
    notification_product_deleted: "Товар успешно удален",
    notification_delete_error: "Ошибка при удалении товара",
    notification_changes_saved: "Изменения успешно сохранены",
    notification_save_error: "Ошибка при сохранении изменений",
    notification_id_exists: "ID %s уже существует"
  },
  en: {
    // Header
    nav_main: "Home",
    nav_masters: "Masters",
    nav_haircuts: "Haircuts",
    nav_catalog: "Catalog",
    nav_cart: "Cart",
    nav_contacts: "Contacts",
    burger_menu: "Menu",
    // Footer
    footer_contacts: "Contacts",
    footer_phone_1: "+7 (812) 123-45-67",
    footer_phone_2: "+7 (911) 123-45-67",
    footer_address: "Novoostrovsky Prospekt, 36 lit.",
    footer_hours: "Working Hours",
    footer_hours_weekdays: "10:00 AM - 9:00 PM (Mon-Fri)",
    footer_hours_weekends: "11:00 AM - 8:00 PM (Sat-Sun)",
    footer_instagram: "We’re on Instagram",
    footer_copyright: "Copyright © 2017 - 2022",
    // Admin catalog page (static elements)
    search_placeholder: "Search...",
    search_button: "Search",
    filter_category_label: "Category:",
    filter_all: "All",
    filter_price_label: "Price:",
    price_min_placeholder: "From",
    price_max_placeholder: "To",
    filter_rating_label: "Rating:",
    rating_any: "Any",
    rating_3_plus: "3+",
    rating_4_plus: "4+",
    rating_4_5_plus: "4.5+",
    filter_sort_label: "Sort by:",
    sort_default: "Default",
    sort_name_asc: "A-Z",
    sort_name_desc: "Z-A",
    sort_price_asc: "Cheapest",
    sort_price_desc: "Most Expensive",
    no_results: "No products found",
    button_save_changes: "Save Changes",
    button_add_product: "Add Product",
    // Admin catalog page (dynamic elements)
    new_product: "New Product",
    placeholder_product_id: "Product ID (unique)",
    placeholder_product_name: "Name",
    placeholder_product_price: "Price",
    placeholder_product_description: "Description",
    placeholder_product_rating: "Rating",
    placeholder_product_image: "Image Path",
    button_delete_product: "Delete Product",
    button_cancel_add: "Cancel Addition",
    // Categories
    category_face: "Face",
    category_body: "Body",
    category_make_up: "Make up",
    category_hairs: "Hairs",
    // Notifications
    notification_product_deleted: "Product successfully deleted",
    notification_delete_error: "Error deleting product",
    notification_changes_saved: "Changes successfully saved",
    notification_save_error: "Error saving changes",
    notification_id_exists: "ID %s already exists"
  }
};