const translations = {
  ru: {
    // Header
    nav_main: "Главная",
    nav_masters: "Мастера",
    nav_haircuts: "Стрижки",
    nav_catalog: "Каталог",
    nav_cart: "Корзина",
    nav_contacts: "Контакты",
    // Footer
    footer_contacts: "Контакты",
    footer_phone_1: "+7 (812) 123-45-67",
    footer_phone_2: "+7 (911) 123-45-67",
    footer_address: "Новоостровский проспект, дом 36 лит.",
    footer_hours: "Режим работы",
    footer_hours_weekdays: "C 10:00 до 21:00 (Пн-Пт)",
    footer_hours_weekends: "С 11:00 до 20:00 (Сб-Вс)",
    footer_instagram: "Мы в Instagram",
    footer_copyright: "Copyright © 2017 - 2022",
    // Catalog page 
    search_placeholder: "Поиск...",
    search_button: "Найти",
    category_label: "Категория:",
    category_all: "Все",
    price_label: "Цена:",
    price_min_placeholder: "От",
    price_max_placeholder: "До",
    rating_label: "Рейтинг:",
    rating_any: "Любой",
    rating_3: "3+",
    rating_4: "4+",
    rating_4_5: "4.5+",
    sort_label: "Сортировка:",
    sort_default: "По умолчанию",
    sort_name_asc: "А-Я",
    sort_name_desc: "Я-А",
    sort_price_asc: "Дешевле",
    sort_price_desc: "Дороже",
    no_results: "Товары не найдены",
    // Catalog page 
    category_face: "Лицо",
    category_body: "Тело",
    category_make_up: "Макияж",
    category_hairs: "Волосы",
  },
  en: {
    // Header
    nav_main: "Home",
    nav_masters: "Masters",
    nav_haircuts: "Haircuts",
    nav_catalog: "Catalog",
    nav_cart: "Cart",
    nav_contacts: "Contacts",
    // Footer
    footer_contacts: "Contacts",
    footer_phone_1: "+7 (812) 123-45-67",
    footer_phone_2: "+7 (911) 123-45-67",
    footer_address: "Novoostrovsky Prospekt, 36 lit.",
    footer_hours: "Working Hours",
    footer_hours_weekdays: "10:00 AM - 9:00 PM (Mon-Fri)",
    footer_hours_weekends: "11:00 AM - 8:00 PM (Sat-Sun)",
    footer_instagram: "We’re on Instagram",
    footer_copyright: "Copyright © 2017 - 2022",
    // Catalog page 
    search_placeholder: "Search...",
    search_button: "Find",
    category_label: "Category:",
    category_all: "All",
    price_label: "Price:",
    price_min_placeholder: "From",
    price_max_placeholder: "To",
    rating_label: "Rating:",
    rating_any: "Any",
    rating_3: "3+",
    rating_4: "4+",
    rating_4_5: "4.5+",
    sort_label: "Sort by:",
    sort_default: "Default",
    sort_name_asc: "A-Z",
    sort_name_desc: "Z-A",
    sort_price_asc: "Cheapest",
    sort_price_desc: "Most Expensive",
    no_results: "No products found",
    // Catalog page 
    category_face: "Face",
    category_body: "Body",
    category_make_up: "Make up",
    category_hairs: "Hairs",
  }
};