const translations = {
  ru: {
    // Header
    nav_main: "Главная",
    nav_masters: "Мастера",
    nav_haircuts: "Стрижки",
    nav_catalog: "Каталог",
    nav_cart: "Корзина",
    nav_contacts: "Контакты",
    // Footer
    footer_contacts: "Контакты",
    footer_phone_1: "+7 (812) 123-45-67",
    footer_phone_2: "+7 (911) 123-45-67",
    footer_address: "Новоостровский проспект, дом 36 лит.",
    footer_hours: "Режим работы",
    footer_hours_weekdays: "C 10:00 до 21:00 (Пн-Пт)",
    footer_hours_weekends: "С 11:00 до 20:00 (Сб-Вс)",
    footer_instagram: "Мы в Instagram",
    footer_copyright: "Copyright © 2017 - 2022",
    // Catalog page (static elements)
    search_placeholder: "Поиск...",
    search_button: "Найти",
    category_label: "Категория:",
    category_all: "Все",
    price_label: "Цена:",
    price_min_placeholder: "От",
    price_max_placeholder: "До",
    rating_label: "Рейтинг:",
    rating_any: "Любой",
    rating_3: "3+",
    rating_4: "4+",
    rating_4_5: "4.5+",
    sort_label: "Сортировка:",
    sort_default: "По умолчанию",
    sort_name_asc: "А-Я",
    sort_name_desc: "Я-А",
    sort_price_asc: "Дешевле",
    sort_price_desc: "Дороже",
    no_results: "Товары не найдены",
    // Catalog page (dynamic elements - categories)
    category_face: "Лицо",
    category_body: "Тело",
    category_make_up: "Макияж",
    category_hairs: "Волосы",
    // Catalog page (dynamic elements - products)
    product_cover_age_3_0_medium_spf50_name: "Крем-пудра Cover-Age 3.0 Medium SPF50+",
    product_cover_age_3_0_medium_spf50_description: "Крем-пудра с тонирующим эффектом",
    product_brightening_serus_name: "Осветляющая сыворотка",
    product_brightening_serus_description: "Осветляющая сыворотка с антиоксидантным действием",
    product_swiss_timeless_fusion_cleanser_name: "Очищающий бальзам Swiss Timeless Fusion",
    product_swiss_timeless_fusion_cleanser_description: "Очищающий бальзам",
    product_swiss_phyto_cells_revitalizing_24h_face_cream_name: "Крем Swiss Phyto Cells Revitalizing 24H",
    product_swiss_phyto_cells_revitalizing_24h_face_cream_description: "Крем с фитоклетками",
    product_stem_cell_plasma_hydro_rescue_concentrate_name: "Концентрат Stem Cell Plasma Hydro Rescue",
    product_stem_cell_plasma_hydro_rescue_concentrate_description: "Омолаживающий концентрат",
    product_sublime_cream_name: "Ночной крем Sublime",
    product_sublime_cream_description: "Активный омолаживающий ночной крем",
    product_booster_with_vitamin_c_name: "Бустер с витамином C",
    product_booster_with_vitamin_c_description: "Набор: сыворотка-бустер с витамином C + пенка для умывания",
    product_lait_velours_name: "Молочко Lait Velours",
    product_lait_velours_description: "Молочко для снятия макияжа",
    product_perfect_glow_name: "Крем Perfect Glow",
    product_perfect_glow_description: "Крем для тела с сиянием и омолаживающим действием",
    product_vodermina_name: "Гель Vidermina",
    product_vodermina_description: "Гель для интимной гигиены для детей",
    product_pistachio_lebroland_name: "Гель Pistachio Lebroland",
    product_pistachio_lebroland_description: "Смягчающий гель для душа Фисташка",
    product_snowman_name: "Бурлящие шары Snowman",
    product_snowman_description: "Бурлящие шары для ванн Снеговичок",
    product_cocoa_with_marshmallows_name: "Крем Cocoa with Marshmallows",
    product_cocoa_with_marshmallows_description: "Крем для тела Какао с зефирками",
    product_crema_corpo_fluida_name: "Лосьон Crema Corpo Fluida",
    product_crema_corpo_fluida_description: "Лосьон для тела Аргания",
    product_solarium_alfaparf_milano_name: "Крем Solarium Alfaparf Milano",
    product_solarium_alfaparf_milano_description: "Смягчающий крем после загара для лица и тела",
    product_iau_lycomint_body_soap_name: "Гель Iau Lycomint Body Soap",
    product_iau_lycomint_body_soap_description: "Освежающий гель для душа",
    product_pease_bb_cream_name: "BB-крем Pease",
    product_pease_bb_cream_description: "BB-крем с гиалуроновой кислотой",
    product_deborah_milano_name: "Помада Deborah Milano",
    product_deborah_milano_description: "Помада-бальзам для губ",
    product_formula_pura_rossetto_liquido_mat_name: "Помада Formula Pura Rossetto Liquido Mat",
    product_formula_pura_rossetto_liquido_mat_description: "Помада матовая жидкая",
    product_jolies_levres_name: "Карандаш Jolies Levres",
    product_jolies_levres_description: "Карандаш для губ",
    product_bionike_mure_005_name: "Блеск BioNike Mure 005",
    product_bionike_mure_005_description: "Блеск для губ тон 005",
    product_lippaque_volume_and_radiance_name: "Блеск Lippaque Volume and Radiance",
    product_lippaque_volume_and_radiance_description: "Блеск для губ тон 601 CAMEO",
    product_ecological_volume_lacquer_name: "Лак Ecological Volume Lacquer",
    product_ecological_volume_lacquer_description: "Лак для объема волос сильной фиксации",
    product_scalp_care_name: "Набор Scalp Care",
    product_scalp_care_description: "Набор для тщательного очищения кожи головы",
    product_service_color_activator_5_vol_name: "Активатор Service Color Activator 5 vol",
    product_service_color_activator_5_vol_description: "Активатор окрашивания волос",
    product_rosemary_lush_name: "Кондиционер Rosemary Lush",
    product_rosemary_lush_description: "Кондиционер для волос",
    product_black_hair_brush_name: "Расческа Black Hair Brush",
    product_black_hair_brush_description: "Расческа для волос",
    product_recharging_elixir_name: "Масло Recharging Elixir",
    product_recharging_elixir_description: "Восстанавливающее масло для волос",
    product_limba_cosmetics_hair_care_name: "Набор Limba Cosmetics Hair Care",
    product_limba_cosmetics_hair_care_description: "Набор для жирной и проблемной кожи головы",
    product_lakmé_gloss_color_rinse_jojoba_oil_name: "Краска Lakmé Gloss Color Rinse+Jojoba Oil",
    product_lakmé_gloss_color_rinse_jojoba_oil_description: "Крем-краска для волос тонирующая безаммиачная"
  },
  en: {
    // Header
    nav_main: "Home",
    nav_masters: "Masters",
    nav_haircuts: "Haircuts",
    nav_catalog: "Catalog",
    nav_cart: "Cart",
    nav_contacts: "Contacts",
    // Footer
    footer_contacts: "Contacts",
    footer_phone_1: "+7 (812) 123-45-67",
    footer_phone_2: "+7 (911) 123-45-67",
    footer_address: "Novoostrovsky Prospekt, 36 lit.",
    footer_hours: "Working Hours",
    footer_hours_weekdays: "10:00 AM - 9:00 PM (Mon-Fri)",
    footer_hours_weekends: "11:00 AM - 8:00 PM (Sat-Sun)",
    footer_instagram: "We’re on Instagram",
    footer_copyright: "Copyright © 2017 - 2022",
    // Catalog page 
    search_placeholder: "Search...",
    search_button: "Find",
    category_label: "Category:",
    category_all: "All",
    price_label: "Price:",
    price_min_placeholder: "From",
    price_max_placeholder: "To",
    rating_label: "Rating:",
    rating_any: "Any",
    rating_3: "3+",
    rating_4: "4+",
    rating_4_5: "4.5+",
    sort_label: "Sort by:",
    sort_default: "Default",
    sort_name_asc: "A-Z",
    sort_name_desc: "Z-A",
    sort_price_asc: "Cheapest",
    sort_price_desc: "Most Expensive",
    no_results: "No products found",
    // Catalog page 
    category_face: "Face",
    category_body: "Body",
    category_make_up: "Make up",
    category_hairs: "Hairs",
    // Catalog page 
    product_cover_age_3_0_medium_spf50_name: "Cover-Age 3.0 Medium SPF50+",
    product_cover_age_3_0_medium_spf50_description: "Tinted cream-powder",
    product_brightening_serus_name: "Brightening Serum",
    product_brightening_serus_description: "Brightening serum with antioxidant action",
    product_swiss_timeless_fusion_cleanser_name: "Swiss Timeless Fusion Cleanser",
    product_swiss_timeless_fusion_cleanser_description: "Cleansing balm",
    product_swiss_phyto_cells_revitalizing_24h_face_cream_name: "Swiss Phyto Cells Revitalizing 24H Face Cream",
    product_swiss_phyto_cells_revitalizing_24h_face_cream_description: "Cream with phyto-cells",
    product_stem_cell_plasma_hydro_rescue_concentrate_name: "Stem Cell Plasma Hydro Rescue Concentrate",
    product_stem_cell_plasma_hydro_rescue_concentrate_description: "Rejuvenating concentrate",
    product_sublime_cream_name: "Sublime Cream",
    product_sublime_cream_description: "Active rejuvenating night cream",
    product_booster_with_vitamin_c_name: "Booster with Vitamin C",
    product_booster_with_vitamin_c_description: "Set: Vitamin C booster serum + cleansing foam",
    product_lait_velours_name: "Lait Velours",
    product_lait_velours_description: "Makeup removal milk",
    product_perfect_glow_name: "Perfect Glow",
    product_perfect_glow_description: "Body cream with glow and rejuvenating effect",
    product_vodermina_name: "Vidermina",
    product_vodermina_description: "Intimate hygiene gel for children",
    product_pistachio_lebroland_name: "Pistachio Lebroland",
    product_pistachio_lebroland_description: "Softening pistachio shower gel",
    product_snowman_name: "Snowman",
    product_snowman_description: "Snowman bath bombs",
    product_cocoa_with_marshmallows_name: "Cocoa with Marshmallows",
    product_cocoa_with_marshmallows_description: "Cocoa and marshmallow body cream",
    product_crema_corpo_fluida_name: "Crema Corpo Fluida",
    product_crema_corpo_fluida_description: "Argan body lotion",
    product_solarium_alfaparf_milano_name: "Solarium Alfaparf Milano",
    product_solarium_alfaparf_milano_description: "Soothing after-sun cream for face and body",
    product_iau_lycomint_body_soap_name: "Iau Lycomint Body Soap",
    product_iau_lycomint_body_soap_description: "Refreshing shower gel",
    product_pease_bb_cream_name: "Pease BB-cream",
    product_pease_bb_cream_description: "BB-cream with hyaluronic acid",
    product_deborah_milano_name: "Deborah Milano",
    product_deborah_milano_description: "Lipstick-balm",
    product_formula_pura_rossetto_liquido_mat_name: "Formula Pura Rossetto Liquido Mat",
    product_formula_pura_rossetto_liquido_mat_description: "Matte liquid lipstick",
    product_jolies_levres_name: "Jolies Levres",
    product_jolies_levres_description: "Lip pencil",
    product_bionike_mure_005_name: "BioNike Mure 005",
    product_bionike_mure_005_description: "Lip gloss shade 005",
    product_lippaque_volume_and_radiance_name: "Lippaque Volume and Radiance",
    product_lippaque_volume_and_radiance_description: "Lip gloss shade 601 CAMEO",
    product_ecological_volume_lacquer_name: "Ecological Volume Lacquer",
    product_ecological_volume_lacquer_description: "Strong hold hair volume lacquer",
    product_scalp_care_name: "Scalp Care",
    product_scalp_care_description: "Set for thorough scalp cleansing",
    product_service_color_activator_5_vol_name: "Service Color Activator 5 vol",
    product_service_color_activator_5_vol_description: "Hair coloring activator",
    product_rosemary_lush_name: "Rosemary Lush",
    product_rosemary_lush_description: "Hair conditioner",
    product_black_hair_brush_name: "Black Hair Brush",
    product_black_hair_brush_description: "Hair brush",
    product_recharging_elixir_name: "Recharging Elixir",
    product_recharging_elixir_description: "Restorative hair oil",
    product_limba_cosmetics_hair_care_name: "Limba Cosmetics Hair Care",
    product_limba_cosmetics_hair_care_description: "Set for oily and problematic scalp",
    product_lakmé_gloss_color_rinse_jojoba_oil_name: "Lakmé Gloss Color Rinse+Jojoba Oil",
    product_lakmé_gloss_color_rinse_jojoba_oil_description: "Ammonia-free toning hair cream-color"
  }
};