const translations = {
  ru: {
    // Footer
    footer_contacts: "Контакты",
    footer_phone_1: "+7 (812) 123-45-67",
    footer_phone_2: "+7 (911) 123-45-67",
    footer_address: "Новоостровский проспект, дом 36 лит.",
    footer_hours: "Режим работы",
    footer_hours_weekdays: "C 10:00 до 21:00 (Пн-Пт)",
    footer_hours_weekends: "С 11:00 до 20:00 (Сб-Вс)",
    footer_instagram: "Мы в Instagram",
    footer_copyright: "Copyright © 2017 - 2022",
    // Registration page 
    register_title: "Регистрация",
    fio_label: "ФИО",
    first_name_placeholder: "Имя",
    last_name_placeholder: "Фамилия",
    middle_name_placeholder: "Отчество",
    phone_label: "Телефон",
    phone_placeholder: "+375XXXXXXXXX",
    email_label: "Email",
    email_placeholder: "Введите email",
    birthdate_label: "Дата рождения",
    password_label: "Пароль",
    password_placeholder: "Пароль (8-20 символов)",
    generate_password_button: "Сгенерировать",
    confirm_password_placeholder: "Повторите пароль",
    nickname_label: "Никнейм",
    generate_nickname_button: "Сгенерировать",
    agreement_label: "Я прочитал и согласен с Соглашением пользователя",
    user_agreement_link: "Соглашением пользователя",
    register_button: "Зарегистрироваться",
    login_link: "Уже есть аккаунт? Войти",
    copy_password_button: "Копировать пароль",
    // Registration page 
    error_first_name_empty: "Укажите имя",
    error_last_name_empty: "Укажите фамилию",
    error_invalid_phone: "Введите корректный номер телефона (+375XXXXXXXXX)",
    error_phone_taken: "Этот телефон уже занят",
    error_invalid_email: "Введите корректный email",
    error_email_taken: "Этот email уже занят",
    error_invalid_birthdate: "Укажите дату рождения",
    error_underage: "Вам должно быть не менее 16 лет для регистрации",
    error_password_length: "Пароль должен содержать от 8 до 20 символов",
    error_password_no_uppercase: "Пароль должен содержать хотя бы одну заглавную букву",
    error_password_no_lowercase: "Пароль должен содержать хотя бы одну строчную букву",
    error_password_no_digit: "Пароль должен содержать хотя бы одну цифру",
    error_password_no_special: "Пароль должен содержать хотя бы один специальный символ",
    error_password_common: "Этот пароль слишком распространен, выберите другой",
    error_password_mismatch: "Пароли не совпадают",
    error_nickname_empty: "Введите никнейм",
    error_nickname_taken: "Этот никнейм уже занят",
    error_agreement_not_checked: "Необходимо принять соглашение",
    notification_password_copied: "Пароль скопирован в буфер обмена"
  },
  en: {
    // Footer
    footer_contacts: "Contacts",
    footer_phone_1: "+7 (812) 123-45-67",
    footer_phone_2: "+7 (911) 123-45-67",
    footer_address: "Novoostrovsky Prospekt, 36 lit.",
    footer_hours: "Working Hours",
    footer_hours_weekdays: "10:00 AM - 9:00 PM (Mon-Fri)",
    footer_hours_weekends: "11:00 AM - 8:00 PM (Sat-Sun)",
    footer_instagram: "We’re on Instagram",
    footer_copyright: "Copyright © 2017 - 2022",
    // Registration page 
    register_title: "Registration",
    fio_label: "Full Name",
    first_name_placeholder: "First Name",
    last_name_placeholder: "Last Name",
    middle_name_placeholder: "Middle Name",
    phone_label: "Phone",
    phone_placeholder: "+375XXXXXXXXX",
    email_label: "Email",
    email_placeholder: "Enter email",
    birthdate_label: "Date of Birth",
    password_label: "Password",
    password_placeholder: "Password (8-20 characters)",
    generate_password_button: "Generate",
    confirm_password_placeholder: "Confirm Password",
    nickname_label: "Nickname",
    generate_nickname_button: "Generate",
    agreement_label: "I have read and agree to the User Agreement",
    user_agreement_link: "User Agreement",
    register_button: "Register",
    login_link: "Already have an account? Sign In",
    copy_password_button: "Copy Password",
    // Registration page 
    error_first_name_empty: "Enter first name",
    error_last_name_empty: "Enter last name",
    error_invalid_phone: "Enter a valid phone number (+375XXXXXXXXX)",
    error_phone_taken: "This phone number is already taken",
    error_invalid_email: "Enter a valid email",
    error_email_taken: "This email is already taken",
    error_invalid_birthdate: "Enter date of birth",
    error_underage: "You must be at least 16 years old to register",
    error_password_length: "Password must be 8-20 characters long",
    error_password_no_uppercase: "Password must contain at least one uppercase letter",
    error_password_no_lowercase: "Password must contain at least one lowercase letter",
    error_password_no_digit: "Password must contain at least one digit",
    error_password_no_special: "Password must contain at least one special character",
    error_password_common: "This password is too common, choose another",
    error_password_mismatch: "Passwords do not match",
    error_nickname_empty: "Enter nickname",
    error_nickname_taken: "This nickname is already taken",
    error_agreement_not_checked: "You must agree to the terms",
    notification_password_copied: "Password copied to clipboard"
  }
};